### ISSUE TITLE
RFC "Keeping O3DE Roadmap Up-to-Date Process" - Tasks Tracker

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-release#128]
This issue's purpose: To provide visibility for tasks related to this RFC: https://github.com/o3de/sig-release/issues/79

### Create a new roadmap item issue template by January 28th, 2023

- [x] https://github.com/o3de/sig-testing/pull/59
- [x] https://github.com/o3de/sig-simulation/pull/37
- [x] https://github.com/o3de/sig-content/pull/104
- [x] https://github.com/o3de/sig-graphics-audio/pull/96
- [x] https://github.com/o3de/sig-release/pull/126
- [x] https://github.com/o3de/sig-docs-community/pull/96
- [x] https://github.com/o3de/sig-operations/pull/40
- [x] https://github.com/o3de/sig-ui-ux/pull/102
- [x] https://github.com/o3de/sig-platform/pull/63
- [x] https://github.com/o3de/sig-core/pull/48
- [x] https://github.com/o3de/sig-build/pull/74
- [x] https://github.com/o3de/sig-security/pull/61
- [x] https://github.com/o3de/sig-network/pull/87

### Ask each SIG to create the roadmap by February 6th, 2023
- [x] https://github.com/o3de/sig-testing/issues/61
- [x] SIG Simulation
- [x] https://github.com/o3de/sig-content/issues/109
- [x] https://github.com/o3de/sig-graphics-audio/issues/115
- [x] https://github.com/o3de/sig-release/issues/127
- [x] https://github.com/o3de/sig-docs-community/issues/97
- [x] https://github.com/o3de/sig-operations/issues/41
- [x] https://github.com/o3de/sig-ui-ux/issues/106
- [x] https://github.com/o3de/sig-platform/issues/64
- [x] https://github.com/o3de/sig-core/issues/49
- [x] https://github.com/o3de/sig-build/issues/75
- [x] https://github.com/o3de/sig-security/issues/64
- [x] https://github.com/o3de/sig-network/issues/90

- [x] Inform TSC about the additional agenda via chat - Done via [Discord](https://discord.com/channels/805939474655346758/816045972865155082/1064798483825037312)
- [x] #137 
- [x] Inform the marketing team of the SIG roadmap once #137 is done.
- [x] #146
```[tasklist]
### Tasks
- [x] Creates a documentation that explains the roadmap process
- [x] Close this issue: https://github.com/o3de/sig-release/issues/79
```

**Comment by vincent6767** [comment]
All tasks are done. Will close the ticket.
