### ISSUE TITLE
Roadmap Item =Simplify the Release Notes tracking process=

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-release#135]
### Summary:
Simplify the Release Notes tracking process

### What is the relevance of this feature?
Context can be read here: https://github.com/o3de/sig-release/discussions/107#discussion-4574025

### Tasks
- [ ] Decides the assignee.
- [ ] Creates RFC and requests feedback from other SIGs
- [ ] Work with the SIG build and operation to set up the bot based on the RFC

### Related Links
[Link to additional information such as RFC related to the roadmap item.](https://github.com/o3de/sig-release/discussions/107)
