### ISSUE TITLE
SIG Release Election 2023

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-release#196]
You can see the election process here: https://github.com/o3de/community/blob/main/O3DE%20Elections/O3DE%20Elections%20Guide.md

```[tasklist]
### Tasks
- [ ] Decides the nomination and election timeline.
- [ ] Finds 1 Election Official
- [ ] Draft the SIG Election and share it with the current SIG Chairs for their input and revisions.
- [ ] Determine the dates and timeline for the election.
- [ ] Create an Election notice on GitHub as a new issue in the SIG, providing all the necessary details, including the SIG name and updated dates. (Consider creating a template for future elections.)
- [ ] Once at least two nominees are confirmed, prepare the voting survey. 
- [ ] Announce the results of the Issue and the SIG Channel
- [ ] Keep the election issue open for about 1 to 2 weeks in case there is an issue that comes up
```

**Comment by vincent6767** [comment]
@tonybalandiuk I propose the following timeline
1. Nomination: July 19th - August 2nd, 2023
2. Election: August 3rd - 10th, 2023.

As for the Election official, I'm thinking to ask Joe to run it. Thoughts? @tonybalandiuk

**Comment by tonybalandiuk** [comment]
@vincent6767  I asked over in Sig-Docs-Community to see if anyone there can help run it. I think it would be great if someone from the community took this role.

As far as the timeline goes, what if we try to get things done sooner? The reason is that we're already discussing the next release, so the sooner they can step in the better

Nomination: July 3 - July 17, 2023. The Election Official will post the Discord event ASAP as a heads up (as soon as we have an Election Official).
Election: July 18 - 25th, 2023.

**Comment by vincent6767** [comment]
Hi @tonybalandiuk 
Sounds good on finding someone from the SIG docs community. I'm also okay with the proposed timeline. I'll update the timeline. Thanks!

**Comment by vincent6767** [comment]
BTW, Chanelle is away for a month. I'll follow up with them again next week.

**Comment by vincent6767** [comment]
@tonybalandiuk FYI, Naomi hasn't responded. I pinged her just today. But if she doesn't answer tomorrow, the timeline will surely be delayed. I wonder do you have any concerns if I ask Joe's help if she doesn't respond?

**Comment by tonybalandiuk** [comment]
@vincent6767 feel free to ask Joe or anyone else. go for it! 
As far as other people, we could always ask JT [SCB_GameDesign] - he participates in a lot of SIG meetings for multiple SIGs

**Comment by vincent6767** [comment]
@tonybalandiuk Thanks. @Naomi-Wash just confirms she is able to help with the election! I have shared with her the next steps.

**Comment by vincent6767** [comment]
According to this checklist, @Naomi-Wash can you help announce Roddie as the next SIG Release co-chair in the SIG release channel?
