### ISSUE TITLE
23.05 Retros Action Items: Missing and optimizing steps in the release.

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-release#201]
```[tasklist]
### Tasks
- [x] Have a discussion with @amzn-mike on [this](https://docs.google.com/spreadsheets/d/1jvPxKBBQTSfkS3jg570jZ9snFaQUUyAtUQu9SBwC1Xc/edit?pli=1#gid=0&range=C4) retros feedback
- [x] Have a discussion with @amzn-mike on [this](https://docs.google.com/spreadsheets/d/1jvPxKBBQTSfkS3jg570jZ9snFaQUUyAtUQu9SBwC1Xc/edit?pli=1#gid=0&range=C15) retros feedback.
- [x] Add [this](https://docs.google.com/spreadsheets/d/1jvPxKBBQTSfkS3jg570jZ9snFaQUUyAtUQu9SBwC1Xc/edit?pli=1#gid=0&range=C3) as part of the release task moving forward
- [x] Update the release tasks based on the discussion
- [x] Ask Tony and Mike to review the tasks
- [x] Create a "Launch Preparation Call" task in the a new project
```

**Comment by vincent6767** [comment]
Updates
1. Added the "Invalidate CDN Cache after the release tag" for the next release: https://github.com/o3de/o3de/issues/16207

**Comment by vincent6767** [comment]
Hi @brianherrera @amzn-mike 

Following up on the retros action items, are there any concerns if we go with this order to avoid waiting too long on installer updates?
1. Merge to main upload, 
2. Create a release tag
3. Update the installer

The other thing we would like to discuss is about creating the release tag, main upload, and [o3debinaries.org](http://o3debinaries.org/) website the day before to save time as stated [here](https://docs.google.com/spreadsheets/d/1jvPxKBBQTSfkS3jg570jZ9snFaQUUyAtUQu9SBwC1Xc/edit?pli=1#gid=0&range=C15).

Is it possible if we go with this approach?

**Comment by amzn-mike** [comment]
Hi @vincent6767, I think you meant to tag @amzn-changml :)

**Comment by vincent6767** [comment]
Ah right. Sorry! @amzn-changml Please take a look at the issue

**Comment by amzn-changml** [comment]
Sure thing. I agree with the approach to get these artifacts ready at least a day ahead. In addition, we're looking to further automate this process and target it for next release

**Comment by vincent6767** [comment]
Thanks, @amzn-changml for confirming. I'll update the release tasks list. Any Github issue that we can monitor for progress? 

Also, any thoughts about this? @amzn-changml 
> Following up on the retros action items, are there any concerns if we go with this order to avoid waiting too long on installer updates?
> 1. Merge to the main upload,
> 2. Create a release tag
> 3. Update the installer

**Comment by amzn-changml** [comment]
No concerns, this order seems reasonable, as long as we agree on the timing.

**Comment by vincent6767** [comment]
Got it. Thanks! @amzn-changml

**Comment by vincent6767** [comment]
> Sure thing. I agree with the approach to get these artifacts ready at least a day ahead. In addition, we're looking to further automate this process and target it for next release

Regarding this, @amzn-changml do you have any GHI that keeps us updated about the process automation progress?

**Comment by tonybalandiuk** [comment]
as I read through https://github.com/o3de/o3de/issues/16292 it's basically creating the release. @vincent6767 we should see if there's anything else we want to do before we do this. Is there anyone that you think we should check with before the code is merged and these builds are created and posted? (I don't know, but I want to think about it a little more)

**Comment by vincent6767** [comment]
> we should see if there's anything else we want to do before we do this. Is there anyone that you think we should check with before the code is merged and these builds are created and posted? (I don't know, but I want to think about it a little more)

@tonybalandiuk Based on [this](https://github.com/o3de/o3de/issues/15621), we need to check the responsibilities of who will help with the merge, release tag creation, and build upload. Is there anything else that comes to your mind? If there is nothing else, then I'm going to create another GHI: "Launch Preparation Call" that includes the tasks list "Release Team" and "Launch Prerequisites" in the https://github.com/o3de/o3de/issues/15621

**Comment by tonybalandiuk** [comment]
@vincent6767  I think that makes sense - create the task. Also, as a reminder, if for any reason you need to change the launch day task list for future releases, please modify this one https://github.com/o3de/o3de/issues/16207

**Comment by vincent6767** [comment]
@tonybalandiuk Created the task: https://github.com/o3de/o3de/issues/16302. I have also created a new project for the next release: https://github.com/orgs/o3de/projects/51 .

**Comment by tonybalandiuk** [comment]
Looks good @vincent6767   I can access the board.
